### ISSUE TITLE
Do you benchmark the code compared to nanoGPT?

### ISSUE THREAD

**Issue by linhduongtuan** [tysam-code/hlb-gpt#1] opened 2023-03-07 14:04 UTC
Dear TySam,
I love your source code so much.
But it seems to run more slowly compared with nanoGPT with the same architecture as I try.
So I have a question do you benchmark the code?
For instance, do you try the same configs and datasets (openwebtext and wikitext-103-v1) and vice versa?
I look forward to hearing about your future results.
Best regards,

Linh

**Comment by tysam-code** [comment] 2023-03-07 20:36
I did! I do probably too much work that doesn't get released in detail (or gets outdated quickly). Especially as in a tweet I don't want to make the mistake of comparison in a way that seems like it's dunking on nanoGPT, which is quite good and is more fully-featured (tradespace and all of that).

So, with that said -- let's figure this issue out! :D :)))

The first question is -- do you have PyTorch 2.0 installed? There's a comment at the top of the code for a good link for that. Though I guess that shouldn't change things too much if you're running both repositories side by side. But just in case it's across different configurations, I want to check that first. Also, do you have speed stats for either one of those?

On my end, last time I checked at least (unless I accidentally introduced a regression, which is absolutely a possibility! :D), hlb-GPT was about like maybe 3-8% faster or so compared to nanoGPT per iteration and had single-digits better performance.

If you let me know your numbers and any of the hyperparams you're running that could help a ton (also, is this on the base branch, or the fork you currently have? :D)

One final note -- thanks so much for your kind Facebook post. I saw it! Looks very cool to me. It was really encouraging because I've spent a ton of hemming/hawing and sweat/blood/tears to try to optimize the code for that exact usecase! So to see you turn it around and use it like that was just 😗👌. Anywho, many thanks again! 🎆 <3😄🐧

Alright, let's figure out this speed issue! :DDDD

**Comment by linhduongtuan** [comment] 2023-03-08 02:37
Hi TySam-Code,
Thank you so much for swift response. And I appreciate so much for your very hard work to 
I am using PyTorch V2 on one RTX 3090 now, indeed I completely forget PT V1. However, you should insert a piece of code line to show PT version while training a model.
I have not measured any speed for either source codes or the datasets. As you know Wikitext-103-raw-v1 is very small compared to Openwebtext, that is why I first get my feeling about something while playing around with a variety of hyperparameter settings including your original setting of course. For instance, I can set Lion optimization with LR = 2e-4 (using Timm + safetensors to reduce trained weights), num_heads = 12, num_blocks = 12, and sequence_length = 1024.

To respect Andrej’s work and be polite, I think you should not release your speed performance. However, it should be better if you can release a default setting like nanoGPT using Openwebtext, for example.
Also, I will double-check my wonder to be sure that I do not make any mistakes while reimplementing your code.
All the best.
Linh

**Comment by linhduongtuan** [comment] 2023-03-22 03:28
@tysam-code I'm wondering why you haven't utilized flash attention in your code, as it could enhance the overall performance.

**Comment by tysam-code** [comment] 2023-03-26 01:37
Flash attention is great! However, I haven't found a clean and fast way to get it to work with the current setup as of yet. It's on the list to investigate in the future (along with a few other types of more-optimal attention reorderings). It does work though if you drop in the necessary components, so feel free to implement it yourself if you need it immediately in the short term!

As for the other items in the message above -- Openwebtext sounds good for a longer training run, though the purpose of this particular repo is mainly tiny experiments that set up and run quickly. The current harness should be compatible with long-term training, however, so if you take a look at it and get it working please do let me know! I'd like to make comparisons on that at some point in the future, though for now staying small and lean is good for the sake of increasing the speed and amount of research we can put out. There is a warning if someone is using PyTorch 1 nowadays -- I'd been thinking about it and I think with the split between torch 1 and 2 in the meantime it is good to have a warning if someone is not using a speed-optimal version. Even on the non-compiled baseline nn.MultiheadedAttention, torch 2 offers a nice speed boost! :D

Hope that helps, feel free to update here if you have any other questions.

**Closed as completed** 2023-04-01 04:02 UTC

**Comment by xidulu** [comment] 2024-09-03 01:55
Hi @tysam-code 

I actually managed to get Openwebtext running in your codebase easily, almost out-of-box, without trouble, using the data preprocessing tool provided by NanoGPT, which converts OWT into `train.bin` and `val.bin` that contain the tokenized version of the dataset.

I simply remove the original dataset construction code and replace them with

```python
train_tokenized = torch.from_numpy(np.memmap(os.path.join(base_dir, 'train.bin'),  mode='r', dtype=np.uint16)).to(torch.int)
eval_tokenized  = torch.from_numpy(np.memmap(os.path.join(base_dir, 'val.bin'),  mode='r', dtype=np.uint16)).to(torch.int)

data = {
    'train': train_tokenized,
    'eval': eval_tokenized
    }
```

But one additional thing I had to do is to NOT load the whole dataset to GPU in the beginning, but instead load the batch when they are sampled, otherwise the memory would blow up.
